spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:file:./database
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      use-new-id-generator-mappings: true
  liquibase:
    change-log: db/changelog/liquibase-changelog.xml
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  servlet:
    session:
      timeout: 5
