--liquibase formatted sql
--changeset dex:create-datatables

create table book
(
    id           integer generated by default as identity
        primary key,
    author       varchar(255),
    class_num    integer,
    name         varchar(255),
    publish_year integer not null,
    publisher    varchar(255),
    quantity     integer not null,
    size         integer not null,
    type         integer
);

create table borrowed_order
(
    id            integer generated by default as identity
        primary key,
    borrow_date   timestamp,
    counter_agent varchar(255),
    quantity      integer not null,
    return_date   timestamp,
    returned      boolean not null,
    book_id       integer
        constraint fkmeqkdmchnvxdpmq9ifywmu0cy
            references book
);

create table school_class
(
    id            integer generated by default as identity
        primary key,
    class_teacher varchar(255),
    name          varchar(255)
);

create table class_order
(
    id              integer generated by default as identity
        primary key,
    quantity        integer not null,
    school_class_id integer
        constraint fkd3nwyyg5xvxvulds7m3rtvo7l
            references school_class,
    book_id         integer
        constraint fkjj65myvuycqun2p71pkfsjmxd
            references book,
    returned        integer not null
);


create table student
(
    id             integer generated by default as identity
        primary key,
    address        varchar(255),
    birth_date     integer not null,
    phone          varchar(255),
    pib            varchar(255),
    schoolclass_id integer
        constraint uk_rlxfi50ld370a37hkjlx3libk
            unique
        constraint fkaey2i6r7hv9o35yrvxt9ypauq
            references school_class
);


create table student_order
(
    id         integer generated by default as identity
        primary key,
    quantity   integer not null,
    returned   integer not null,
    take_date  date,
    book_id    integer
        constraint fkhtdvaa4b5tdnbe9but3poqi6c
            references book,
    student_id integer
        constraint fkp7i7ghopadntmevt3dpt1nt2e
            references student
);


create table teacher
(
    id         integer generated by default as identity
        primary key,
    address    varchar(255),
    birth_date integer not null,
    phone      varchar(255),
    pib        varchar(255),
    profession varchar(255)
);


create table teacher_order
(
    id         integer generated by default as identity
        primary key,
    quantity   integer not null,
    returned   integer not null,
    take_date  date,
    book_id    integer
        constraint fktohh5vqxjffw6c38jfh4upywu
            references book,
    teacher_id integer
        constraint fklqqpq1exoukc457qvqi2uwlj7
            references teacher
);
